/*
 * Peridot guided-tutorial step configuration.
 *
 * This module is the single ordered source of truth for tutorial progression.
 * Later bounded passes can add target-specific availability checks and action
 * completion rules without redistributing tutorial copy or routing decisions
 * through App.jsx.
 */

export const PERIDOT_TUTORIAL_STEPS = Object.freeze([
  {
    id: 'visualizations',
    number: 1,
    workspace: 'visualizations',
    title: 'VISUALIZATIONS',
    frames: Object.freeze([
      'A visualization arranges the same records in a form that makes patterns easier to notice.',
      'Maps emphasize locations and routes, while networks emphasize relationships between people or other entities.',
      'Changing the visualization changes the presentation, not the underlying records.',
    ]),
    description: 'A visualization arranges the same records in a different way so patterns are easier to notice. Maps show locations and routes, while networks show relationships between people or other entities.',
    note: 'Changing the view does not change the records. It changes how Peridot presents them.',
    anchorSelector: '[data-peridot-workspace-mode="visualizations"] button[aria-label^="Export "]',
    anchorAncestorText: 'Visualization workspace',
    anchorAncestorMinWidthRatio: 0.72,
    anchorPlacement: 'bottom-right',
    highlightAnchor: true,
  },
  {
    id: 'timeline',
    number: 2,
    workspace: 'visualizations',
    title: 'TIMELINE',
    frames: Object.freeze([
      'The Timeline shows when dated records in the current working set occur.',
      'Drag either range handle to focus on a narrower period.',
      'Playback reveals dated records in sequence without changing the uploaded data.',
    ]),
    description: 'Use the range handles to focus on part of the collection, or use playback to reveal dated records in sequence. Try either kind of control to see the visualization update.',
    note: 'The timeline changes what is currently visible. It does not delete records or change your uploaded data.',
    interactionType: 'timeline',
    interactionPrompt: 'Try moving a range handle, choosing All dates, changing playback position, or using a playback control.',
    interactionCompleteText: 'Timeline change detected. Your selected range or playback state will remain in place when you continue.',
    skipLabel: 'Continue without changing it',
    unavailableText: 'This dataset has no usable Timeline dates, so you can continue without changing anything.',
    anchorSelector: '[data-peridot-workspace-mode="visualizations"] input[type="range"]',
    anchorAncestorText: 'Timeline',
    anchorAncestorMinWidthRatio: 0.72,
    anchorPlacement: 'top-right',
    highlightAnchor: true,
  },
  {
    id: 'inspector',
    number: 3,
    workspace: 'visualizations',
    title: 'INSPECTOR',
    frames: Object.freeze([
      'Visualizations help you notice patterns across the collection.',
      'Select a visible place, person, connection, or group to inspect the evidence behind it.',
      'The Inspector keeps the selected records connected to the pattern you noticed.',
    ]),
    description: 'Select any visible place, person, connection, or group in the map or network. Peridot will open the compact Inspector with details about what you selected.',
    note: 'A visualization helps you notice a pattern. The Inspector helps you check the records behind it.',
    interactionType: 'inspector',
    interactionPrompt: 'Select any node, route, or cluster in the visualization. You do not need to choose a particular item.',
    interactionCompleteText: 'Selection detected. The compact Inspector now summarizes the evidence connected to this item.',
    expandedText: 'The full Inspector is open. It uses the same selection and preserves the visualization underneath.',
    skipLabel: 'Continue without selecting',
    unavailableText: 'The current view has no selectable map or network item, so you can continue to the next part of the tour.',
    selectionAnchorSelector: '[data-peridot-tutorial-anchor="visualization-stage"]',
    selectionAnchorPlacement: 'top-right',
    compactAnchorSelector: 'button',
    compactAnchorMatchText: 'Expand Inspector',
    compactAnchorAncestorText: 'Inspector',
    compactAnchorAncestorMinWidthRatio: 0.16,
    compactAnchorPlacement: 'center-right',
    fullAnchorSelector: '[aria-label="Inspector workspace"]',
    fullAnchorPlacement: 'bottom-right',
    highlightAnchor: true,
  },
  {
    id: 'explore',
    number: 4,
    workspace: 'visualizations',
    title: 'EXPLORE',
    frames: Object.freeze([
      'Explore is where you browse the collection and build a focused search.',
      'You can reach it from either the top Explore control or the main Peridot menu.',
      'Your visualization, Timeline range, and applied filters remain available when you move between workspaces.',
    ]),
    description: 'Use the main Peridot menu to move between workspaces. Open the menu, then choose Explore Your Data.',
    note: 'Your visualization, timeline range, and applied filters remain available when you move between workspaces.',
    interactionType: 'explore-navigation',
    menuClosedPrompt: 'Open the main menu with the round button at the upper left.',
    menuOpenPrompt: 'The menu is open. Choose Explore Your Data.',
    reachedText: 'Explore is open, where you can browse the collection and build a focused search.',
    fallbackLabel: 'Open Explore directly',
    inspectorPrompt: 'Close the Inspector before continuing so it does not cover the menu or the next tutorial steps.',
    inspectorCloseLabel: 'Close Inspector',
    inspectorCompactAnchorSelector: 'button',
    inspectorCompactAnchorMatchText: 'Expand',
    inspectorCompactAnchorAncestorText: 'Inspector',
    inspectorCompactAnchorAncestorMinWidthRatio: 0.16,
    inspectorCompactAnchorPlacement: 'center-right',
    inspectorFullAnchorSelector: '[aria-label="Inspector workspace"]',
    inspectorFullAnchorPlacement: 'bottom-right',
    closedAnchorSelector: 'button',
    closedAnchorMatchText: '≡',
    closedAnchorPlacement: 'center-right',
    openAnchorSelector: 'button',
    openAnchorMatchText: 'Explore Your Data',
    openAnchorPlacement: 'center-right',
    reachedAnchorSelector: '[data-peridot-workspace-mode="explore"], [data-peridot-workspace-mode="search"]',
    reachedAnchorPlacement: 'top-right',
    highlightAnchor: true,
  },
  {
    id: 'browse-apply',
    number: 5,
    workspace: 'search',
    title: 'SEARCH',
    frames: Object.freeze([
      'Browse lets you choose a person or place from the full loaded collection.',
      'Your choice first becomes a draft so you can review it before changing the working set.',
      'Apply Filters turns the draft into the active search used across Peridot.',
    ]),
    description: 'Browse the collection, choose any person or place, then apply the draft filter to create a smaller working set.',
    note: 'Choosing an item prepares a draft. Nothing changes across Peridot until you select Apply Filters.',
    interactionType: 'search-browse-apply',
    browsePrompt: 'Open Browse, then choose any person or place that interests you.',
    draftPrompt: 'Your choice is now a draft. Select Apply Filters to update the working set.',
    appliedText: 'The Results tab now shows the applied working set. Maps, networks, charts, Inspector, and exports can use this applied scope.',
    openBrowseLabel: 'Open Browse',
    useCurrentResultsLabel: 'Use current results',
    unavailableText: 'The current dataset has no searchable records, so you can continue with the empty result set.',
    applyLabel: 'Apply Filters',
    browseAnchorSelector: 'button',
    browseAnchorMatchText: 'Browse',
    browseAnchorPlacement: 'bottom-right',
    applyAnchorSelector: 'button',
    applyAnchorMatchText: 'Apply Filters',
    applyAnchorPlacement: 'center-left',
    resultsAnchorSelector: 'button',
    resultsAnchorMatchText: 'Results',
    resultsAnchorPlacement: 'bottom-right',
    highlightAnchor: true,
  },
  {
    id: 'working-set',
    number: 6,
    workspace: 'search',
    title: 'SCOPE',
    frames: Object.freeze([
      'The records matching your applied search become Peridot’s working set.',
      'Maps, networks, charts, the Inspector, and exports can all use that applied scope.',
      'Timeline and chart controls can narrow an individual view without changing the applied search.',
    ]),
    description: 'The records that match your applied search become the working set Peridot uses across its research tools.',
    note: 'Individual views can narrow what you see further—for example, with the timeline or chart settings—without changing the applied search itself.',
    interactionType: 'working-set-explanation',
    flowStart: 'All loaded records',
    flowMiddle: 'Your applied search',
    flowEnd: 'Maps, networks, charts, Inspector, and exports',
    anchorSelector: 'button',
    anchorMatchText: 'Results',
    anchorPlacement: 'bottom-right',
    highlightAnchor: true,
  },
  {
    id: 'export',
    number: 7,
    workspace: 'visualizations',
    title: 'EXPORT',
    frames: Object.freeze([
      'Export saves the current map, network, chart, or data table for use elsewhere.',
      'The available image and data formats depend on the active visualization.',
      'Opening the Export menu does not create or download a file.',
    ]),
    description: 'Export lets you save the current map, network, chart, or data table for a presentation, report, or further analysis.',
    note: 'Available formats depend on the active view. Opening Export does not download anything.',
    interactionType: 'export-completion',
    closedPrompt: 'Open Export to review the formats available for the current visualization.',
    openText: 'The Export menu is open. Review the available image and data formats; choose one only when you actually want to create a file.',
    completeTitle: 'COMPLETE',
    completeText: 'You can now load records, choose a view, explore time, inspect evidence, search the collection, and save a result.',
    unavailableText: 'The current view has nothing exportable, so you can finish the tour or return to another visualization later.',
    closedAnchorSelector: 'button',
    closedAnchorMatchText: 'Export',
    closedAnchorPlacement: 'center-left',
    openAnchorSelector: 'button',
    openAnchorMatchText: 'Export visualization SVG',
    openAnchorAncestorText: 'Export',
    openAnchorAncestorMinWidthRatio: 0.12,
    openAnchorPlacement: 'center-left',
    highlightAnchor: true,
  },
]);

export const PERIDOT_TUTORIAL_TOTAL_STEPS = PERIDOT_TUTORIAL_STEPS.length;
export const PERIDOT_TUTORIAL_START_INDEX = 0;

export function getPeridotTutorialStep(stepIndex) {
  const safeIndex = Math.min(
    Math.max(0, Number.isInteger(stepIndex) ? stepIndex : PERIDOT_TUTORIAL_START_INDEX),
    PERIDOT_TUTORIAL_STEPS.length - 1,
  );

  return PERIDOT_TUTORIAL_STEPS[safeIndex];
}

export function getPeridotTutorialStepIndex(stepId) {
  const index = PERIDOT_TUTORIAL_STEPS.findIndex((step) => step.id === stepId);
  return index >= 0 ? index : PERIDOT_TUTORIAL_START_INDEX;
}
